/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RegisterLecturerRouteImport } from './routes/register.lecturer'
import { Route as RegisterStudentRouteImport } from './routes/register.student'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAttendanceSessionIdRouteImport } from './routes/student.attendance.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterLecturerRoute = RegisterLecturerRouteImport.update({
  id: '/register/lecturer',
  path: '/register/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register/student',
  path: '/register/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceSessionIdRoute =
  StudentAttendanceSessionIdRouteImport.update({
    id: '/student/attendance/$sessionId',
    path: '/student/attendance/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register/lecturer': typeof RegisterLecturerRoute
  '/register/student': typeof RegisterStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/attendance/$sessionId': typeof StudentAttendanceSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register/lecturer': typeof RegisterLecturerRoute
  '/register/student': typeof RegisterStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/attendance/$sessionId': typeof StudentAttendanceSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register/lecturer': typeof RegisterLecturerRoute
  '/register/student': typeof RegisterStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/attendance/$sessionId': typeof StudentAttendanceSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/overview'
    | '/register/lecturer'
    | '/register/student'
    | '/student/dashboard'
    | '/student/attendance/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/overview'
    | '/register/lecturer'
    | '/register/student'
    | '/student/dashboard'
    | '/student/attendance/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/overview'
    | '/register/lecturer'
    | '/register/student'
    | '/student/dashboard'
    | '/student/attendance/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  RegisterLecturerRoute: typeof RegisterLecturerRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentAttendanceSessionIdRoute: typeof StudentAttendanceSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/lecturer': {
      id: '/register/lecturer'
      path: '/register/lecturer'
      fullPath: '/register/lecturer'
      preLoaderRoute: typeof RegisterLecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/student': {
      id: '/register/student'
      path: '/register/student'
      fullPath: '/register/student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance/$sessionId': {
      id: '/student/attendance/$sessionId'
      path: '/student/attendance/$sessionId'
      fullPath: '/student/attendance/$sessionId'
      preLoaderRoute: typeof StudentAttendanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  RegisterLecturerRoute: RegisterLecturerRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentAttendanceSessionIdRoute: StudentAttendanceSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
